language: ruby

sudo: required

services:
  - docker

before_install:
  - echo "Installing test gems then the azure cli"
  - gem install jsonlint
  - sudo apt-get install jq
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - sudo apt-get update && sudo apt-get install azure-cli
  - az login `echo $AZURE_TRAVIS_SERVICE_CREDENTIALS | base64 -d`

  
install: true

script:
  - AZURELOCATION=centralus
  - # Deploying and testing Public exposure
  - jsonlint nestedtemplates/*
  - UNIQUEID="$(date +%s)"
  - TESTRESOURCEGROUPNAME="TravisTestResourceGroup${UNIQUEID}"
  - export ADMINPASSWORD=TravisAdminpwd1234!
  - sed -i "s@ARTIFACTSLOCATION@$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH@g" ci/azuredeploy.parameters.json
  - sed -i "s@UNIQUEID@$UNIQUEID@g" ci/azuredeploy.parameters.json
  - sed -i "s@solace/solace-pubsub-standard:latest@${SOLACE_DOCKER_URL_PARAMETER_VALUE}@g" ci/azuredeploy.parameters.json
  - sed -i "s@ADMINPASSWORD@$ADMINPASSWORD@g" ci/azuredeploy.parameters.json
  - sed -i "s@EXPOSURE@Public@g" ci/azuredeploy.parameters.json
  - cat ci/azuredeploy.parameters.json
  - az group create --name $TESTRESOURCEGROUPNAME --location $AZURELOCATION
  - echo "Creating publicly exposed cluster and waiting to become active"
  - "travis_wait 30 sleep 1800 &"
  - az deployment group create --name TravisTestDeployment${UNIQUEID} --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
  - az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
  - export url=`az network public-ip show --resource-group $TESTRESOURCEGROUPNAME --name myLBPublicIPD --query [ipAddress] --output tsv`; echo $url
  - curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
  - tar -xvf SDKPERF_C_LINUX64
  - pubSubTools/sdkperf_c -cip=$url -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"
  - sleep 30
  - bash -c 'if [[ -z `curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>" | grep "<oper-status>Up</oper-status>"` ]] ; then echo "config-sync not up!"; exit 1; fi'
  - curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><redundancy></redundancy></show></rpc>"
  - curl -sS -u admin:$ADMINPASSWORD http://$url:8080/SEMP -d "<rpc><show><config-sync></config-sync></show></rpc>"
  - az group delete --name $TESTRESOURCEGROUPNAME --yes
  - # Deploying and testing Internal exposure
  - UNIQUEID="$(date +%s)"
  - TESTRESOURCEGROUPNAME="TravisTestResourceGroup${UNIQUEID}"
  - sed -i 's@"Public"@"Internal"@g' ci/azuredeploy.parameters.json
  - sed -i "s@\"travisws.*@\"travisws${UNIQUEID}\"@g" ci/azuredeploy.parameters.json
  - cat ci/azuredeploy.parameters.json
  - az group create --name $TESTRESOURCEGROUPNAME --location $AZURELOCATION
  - echo "Creating internally exposed cluster and waiting to become active"
  - az deployment group create --name TravisTestDeployment${UNIQUEID} --resource-group $TESTRESOURCEGROUPNAME --template-file azuredeploy.json --parameters ci/azuredeploy.parameters.json
  - az group show --name $TESTRESOURCEGROUPNAME | grep provisioningState
  - az network vnet subnet create  --address-prefixes "10.0.1.0/24" --name VmTestSubnet -g $TESTRESOURCEGROUPNAME --vnet-name solace-vnet
  - az vm create   --resource-group $TESTRESOURCEGROUPNAME --name myVM   --image UbuntuLTS  --vnet-name solace-vnet  --subnet VmTestSubnet --admin-username azureuser   --generate-ssh-keys
  - VM_IP=`az vm show -d -g $TESTRESOURCEGROUPNAME -n myVM --query publicIps -o tsv`
  - LB_IP=`az network lb show -g $TESTRESOURCEGROUPNAME -n solace-ha-group-loadbalancer    --query "frontendIpConfigurations[].privateIpAddress" -o tsv`
  - echo ${VM_IP}
  - echo ${LB_IP}
  - ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl ${LB_IP}:8080" | grep aurelia
  - ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl -sS -u admin:$ADMINPASSWORD http://${LB_IP}:8080/SEMP -d \"<rpc><show><redundancy></redundancy></show></rpc>\" "
  - ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64 ; tar -xvf SDKPERF_C_LINUX64"
  - ssh -o StrictHostKeyChecking=no azureuser@${VM_IP} "pubSubTools/sdkperf_c -cip=${LB_IP}:55555 -mn=100000 -mr=0 -ptl=t1 -stl=t1" | grep "Total Messages"
  - az group delete --name $TESTRESOURCEGROUPNAME --yes

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "JSON linted"
  - echo "Cluster deployment tested"
  - echo "Messaging tested"

